/**
 * Planet archetypes — shared by terrain generation (world/planetgen), cosmos (system/galaxy views)
 * and simulation (needs oxygen? hazards?). CONTRACT: ids are PlanetTypeId; append fields freely.
 */
import { Biome, Feature, type PlanetTypeId, type StyleId } from '../core/types';

export interface PlanetArchetype {
  id: PlanetTypeId;
  name: string;
  tagline: string;
  description: string;
  hasOcean: boolean;
  /** fraction of the surface under water at default sea level */
  oceanCoverage: number;
  oceanColor: number;
  atmosphere: { color: number; density: number; breathable: boolean };
  temperature: number;
  gravity: [number, number];
  cloudCover: number;
  /** elevation-banded biome palette used by planetgen (low → high), plus polar & shore */
  biomes: { low: Biome[]; mid: Biome[]; high: Biome[]; peak: Biome; polar: Biome; shore: Biome; seabed: Biome };
  /** chance per eligible land tile */
  features: Partial<Record<Feature, number>>;
  /** base colours used by the terrain renderer for its biome tinting */
  palette: { land: number; lowland: number; highland: number; shore: number; snow: number; rock: number };
  defaultStyle: StyleId;
  /** colonies here need oxygen production */
  needsOxygen: boolean;
  /** natural disaster flavour, weighted for random events */
  hazards: string[];
  /** resource bonuses (flavour + sim multipliers) */
  resources: string[];
  ringChance: number;
  moons: [number, number];
  frequency: [number, number];
  /** 0..1 how rough the terrain is by default */
  ruggedness: number;
}

export const PLANET_TYPES: Record<PlanetTypeId, PlanetArchetype> = {
  terran: {
    id: 'terran',
    name: 'Terran',
    tagline: 'Blue oceans, green continents — a cradle world.',
    description: 'Temperate continents, forests, snowy poles and breathable air. The perfect place to found a civilisation.',
    hasOcean: true,
    oceanCoverage: 0.55,
    oceanColor: 0x1d6fb8,
    atmosphere: { color: 0x6fb6ff, density: 1, breathable: true },
    temperature: 15,
    gravity: [0.9, 1.1],
    cloudCover: 0.45,
    biomes: { low: [Biome.Grass, Biome.Meadow, Biome.Forest], mid: [Biome.Forest, Biome.Grass, Biome.Savanna], high: [Biome.Rock, Biome.Tundra], peak: Biome.Snow, polar: Biome.Snow, shore: Biome.Beach, seabed: Biome.Ocean },
    features: { [Feature.Trees]: 0.22, [Feature.DenseTrees]: 0.12, [Feature.Rocks]: 0.04, [Feature.Ore]: 0.02, [Feature.Flowers]: 0.05, [Feature.Ruins]: 0.003, [Feature.GeoVent]: 0.004 },
    palette: { land: 0x5f9e4a, lowland: 0x7fb85a, highland: 0x7d7a60, shore: 0xe8d8a0, snow: 0xf2f6ff, rock: 0x8a8578 },
    defaultStyle: 'classic',
    needsOxygen: false,
    hazards: ['tornado', 'earthquake', 'tsunami', 'wildfire', 'meteor'],
    resources: ['timber', 'farmland', 'ore'],
    ringChance: 0.15,
    moons: [1, 2],
    frequency: [36, 44],
    ruggedness: 0.5,
  },
  desert: {
    id: 'desert',
    name: 'Desert',
    tagline: 'Endless dunes under twin suns.',
    description: 'Arid canyons, salt flats and rare oases. Water is precious; solar power is abundant.',
    hasOcean: true,
    oceanCoverage: 0.12,
    oceanColor: 0x2a9db0,
    atmosphere: { color: 0xffb36b, density: 0.7, breathable: true },
    temperature: 42,
    gravity: [0.8, 1.2],
    cloudCover: 0.08,
    biomes: { low: [Biome.Desert, Biome.Salt], mid: [Biome.Desert, Biome.Savanna], high: [Biome.Rock, Biome.Mountain], peak: Biome.Rock, polar: Biome.Tundra, shore: Biome.Beach, seabed: Biome.Ocean },
    features: { [Feature.Rocks]: 0.1, [Feature.Ore]: 0.04, [Feature.GasVent]: 0.02, [Feature.Ruins]: 0.008, [Feature.Trees]: 0.02 },
    palette: { land: 0xd9a35f, lowland: 0xe6be7d, highland: 0xa8673c, shore: 0xf2deb0, snow: 0xf0e6d0, rock: 0x8c5a3a },
    defaultStyle: 'mars',
    needsOxygen: false,
    hazards: ['sandstorm', 'meteor', 'heatwave', 'earthquake'],
    resources: ['solar', 'ore', 'gas'],
    ringChance: 0.2,
    moons: [0, 2],
    frequency: [30, 40],
    ruggedness: 0.6,
  },
  arctic: {
    id: 'arctic',
    name: 'Arctic',
    tagline: 'A frozen jewel of ice and aurora.',
    description: 'Glaciers, frozen seas and shimmering auroras. Bitter cold demands heating and robust power.',
    hasOcean: true,
    oceanCoverage: 0.35,
    oceanColor: 0x3a7fa8,
    atmosphere: { color: 0xbfe6ff, density: 0.8, breathable: true },
    temperature: -35,
    gravity: [0.8, 1.1],
    cloudCover: 0.35,
    biomes: { low: [Biome.Snow, Biome.Ice, Biome.Tundra], mid: [Biome.Tundra, Biome.Snow], high: [Biome.Ice, Biome.Rock], peak: Biome.Ice, polar: Biome.Ice, shore: Biome.Snow, seabed: Biome.Ocean },
    features: { [Feature.IceDeposit]: 0.06, [Feature.Rocks]: 0.05, [Feature.Trees]: 0.06, [Feature.GeoVent]: 0.01, [Feature.CrystalDeposit]: 0.01 },
    palette: { land: 0xdfeefa, lowland: 0xc6dceb, highland: 0x9fb4c6, shore: 0xe9f4ff, snow: 0xffffff, rock: 0x6f7f90 },
    defaultStyle: 'ice',
    needsOxygen: false,
    hazards: ['blizzard', 'icequake', 'meteor', 'avalanche'],
    resources: ['ice', 'geothermal'],
    ringChance: 0.25,
    moons: [0, 3],
    frequency: [30, 40],
    ruggedness: 0.45,
  },
  volcanic: {
    id: 'volcanic',
    name: 'Volcanic',
    tagline: 'Rivers of fire beneath an ashen sky.',
    description: 'Basalt plains, lava seas and constant eruptions. Geothermal energy is limitless — if you survive.',
    hasOcean: false,
    oceanCoverage: 0,
    oceanColor: 0xff5a1a,
    atmosphere: { color: 0xff7a3d, density: 1.2, breathable: false },
    temperature: 160,
    gravity: [1.0, 1.4],
    cloudCover: 0.3,
    biomes: { low: [Biome.Lava, Biome.Volcanic], mid: [Biome.Volcanic, Biome.Ash], high: [Biome.Ash, Biome.Rock], peak: Biome.Volcanic, polar: Biome.Ash, shore: Biome.Volcanic, seabed: Biome.Lava },
    features: { [Feature.GeoVent]: 0.06, [Feature.Ore]: 0.06, [Feature.Rocks]: 0.08, [Feature.CrystalDeposit]: 0.01 },
    palette: { land: 0x3a2e2c, lowland: 0x2a2020, highland: 0x55443c, shore: 0x241a18, snow: 0x6d6560, rock: 0x4a3a34 },
    defaultStyle: 'cyber',
    needsOxygen: true,
    hazards: ['eruption', 'lavaflow', 'quake', 'meteor'],
    resources: ['geothermal', 'ore', 'obsidian'],
    ringChance: 0.1,
    moons: [0, 2],
    frequency: [28, 38],
    ruggedness: 0.8,
  },
  ocean: {
    id: 'ocean',
    name: 'Ocean',
    tagline: 'A world-spanning sea dotted with atolls.',
    description: 'Archipelagos and coral reefs scattered across an endless ocean. Build floating districts and sea cities.',
    hasOcean: true,
    oceanCoverage: 0.85,
    oceanColor: 0x0e7fa8,
    atmosphere: { color: 0x7fd0ff, density: 1.1, breathable: true },
    temperature: 24,
    gravity: [0.9, 1.1],
    cloudCover: 0.55,
    biomes: { low: [Biome.Beach, Biome.Jungle, Biome.Grass], mid: [Biome.Jungle, Biome.Forest], high: [Biome.Rock], peak: Biome.Rock, polar: Biome.Ice, shore: Biome.Beach, seabed: Biome.Coral },
    features: { [Feature.Trees]: 0.3, [Feature.DenseTrees]: 0.15, [Feature.Kelp]: 0.1, [Feature.Ruins]: 0.004 },
    palette: { land: 0x4fae5c, lowland: 0x69c06a, highland: 0x6e7a5a, shore: 0xf6e7b8, snow: 0xf2f6ff, rock: 0x7a7468 },
    defaultStyle: 'neo',
    needsOxygen: false,
    hazards: ['hurricane', 'tsunami', 'kraken', 'meteor'],
    resources: ['fish', 'tidal', 'tourism'],
    ringChance: 0.15,
    moons: [1, 3],
    frequency: [36, 48],
    ruggedness: 0.35,
  },
  jungle: {
    id: 'jungle',
    name: 'Jungle',
    tagline: 'A humid green wilderness teeming with life.',
    description: 'Towering rainforests, misty rivers and bioluminescent nights. Fertile, wet and wild.',
    hasOcean: true,
    oceanCoverage: 0.35,
    oceanColor: 0x1f8a7a,
    atmosphere: { color: 0x9cffb0, density: 1.3, breathable: true },
    temperature: 31,
    gravity: [1.0, 1.2],
    cloudCover: 0.6,
    biomes: { low: [Biome.Swamp, Biome.Jungle], mid: [Biome.Jungle, Biome.Forest], high: [Biome.Forest, Biome.Rock], peak: Biome.Rock, polar: Biome.Tundra, shore: Biome.Beach, seabed: Biome.Ocean },
    features: { [Feature.DenseTrees]: 0.35, [Feature.Trees]: 0.2, [Feature.Flowers]: 0.05, [Feature.Ruins]: 0.01, [Feature.AlienFlora]: 0.03 },
    palette: { land: 0x2e8a3c, lowland: 0x3fa048, highland: 0x56704a, shore: 0xd9cf9a, snow: 0xe6f0e6, rock: 0x5e6450 },
    defaultStyle: 'solarpunk',
    needsOxygen: false,
    hazards: ['monsoon', 'wildfire', 'plague', 'kaiju'],
    resources: ['timber', 'biotech', 'farmland'],
    ringChance: 0.1,
    moons: [1, 2],
    frequency: [34, 44],
    ruggedness: 0.5,
  },
  barren: {
    id: 'barren',
    name: 'Barren Moon',
    tagline: 'Silent grey craters and a black sky.',
    description: 'Airless regolith plains pocked by ancient impacts. Everything must be pressurised — but the view of the stars is unmatched.',
    hasOcean: false,
    oceanCoverage: 0,
    oceanColor: 0x000000,
    atmosphere: { color: 0x9aa4b8, density: 0.05, breathable: false },
    temperature: -120,
    gravity: [0.15, 0.4],
    cloudCover: 0,
    biomes: { low: [Biome.Crater, Biome.Regolith], mid: [Biome.Regolith], high: [Biome.Rock, Biome.Regolith], peak: Biome.Rock, polar: Biome.Ice, shore: Biome.Regolith, seabed: Biome.Crater },
    features: { [Feature.Rocks]: 0.12, [Feature.Ore]: 0.05, [Feature.IceDeposit]: 0.02, [Feature.Crater]: 0.04, [Feature.Ruins]: 0.004 },
    palette: { land: 0x9b9b9b, lowland: 0x7f7f80, highland: 0xb4b4b4, shore: 0x8c8c8c, snow: 0xdadada, rock: 0x6b6b6b },
    defaultStyle: 'neo',
    needsOxygen: true,
    hazards: ['meteor', 'solarflare', 'moonquake'],
    resources: ['helium3', 'ore'],
    ringChance: 0,
    moons: [0, 0],
    frequency: [20, 28],
    ruggedness: 0.55,
  },
  toxic: {
    id: 'toxic',
    name: 'Toxic',
    tagline: 'Acid seas under a poison-green sky.',
    description: 'Corrosive swamps and sulfur seas. Hostile, but rich in exotic chemicals for advanced industry.',
    hasOcean: true,
    oceanCoverage: 0.4,
    oceanColor: 0x7fbf1f,
    atmosphere: { color: 0xc8ff4a, density: 1.6, breathable: false },
    temperature: 65,
    gravity: [0.9, 1.3],
    cloudCover: 0.7,
    biomes: { low: [Biome.Toxic, Biome.Swamp], mid: [Biome.Toxic, Biome.Ash], high: [Biome.Rock, Biome.Ash], peak: Biome.Rock, polar: Biome.Salt, shore: Biome.Salt, seabed: Biome.Toxic },
    features: { [Feature.GasVent]: 0.08, [Feature.AlienFlora]: 0.08, [Feature.Rocks]: 0.06, [Feature.Ore]: 0.02 },
    palette: { land: 0x6b7a2a, lowland: 0x8a9a2a, highland: 0x5a5a3a, shore: 0xc9c98a, snow: 0xe0e8b0, rock: 0x4a4a32 },
    defaultStyle: 'cyber',
    needsOxygen: true,
    hazards: ['acidrain', 'plague', 'eruption', 'meteor'],
    resources: ['chemicals', 'gas'],
    ringChance: 0.25,
    moons: [0, 2],
    frequency: [30, 40],
    ruggedness: 0.5,
  },
  crystal: {
    id: 'crystal',
    name: 'Crystal',
    tagline: 'Glittering spires of living crystal.',
    description: 'A world of singing crystal forests and prismatic light. Crystal resonance powers exotic technology.',
    hasOcean: true,
    oceanCoverage: 0.25,
    oceanColor: 0x7a4fd0,
    atmosphere: { color: 0xd59cff, density: 0.9, breathable: false },
    temperature: -5,
    gravity: [0.6, 0.9],
    cloudCover: 0.2,
    biomes: { low: [Biome.Crystal, Biome.Salt], mid: [Biome.Crystal, Biome.Rock], high: [Biome.Crystal, Biome.Ice], peak: Biome.Crystal, polar: Biome.Ice, shore: Biome.Salt, seabed: Biome.Crystal },
    features: { [Feature.CrystalDeposit]: 0.18, [Feature.AlienFlora]: 0.05, [Feature.Rocks]: 0.04, [Feature.Ruins]: 0.01 },
    palette: { land: 0x8e7ad9, lowland: 0xb29cf0, highland: 0x5f4fa8, shore: 0xe8defa, snow: 0xf6f0ff, rock: 0x4a3f7a },
    defaultStyle: 'crystal',
    needsOxygen: true,
    hazards: ['resonance', 'meteor', 'shatterquake'],
    resources: ['crystal', 'research'],
    ringChance: 0.4,
    moons: [0, 3],
    frequency: [28, 40],
    ruggedness: 0.6,
  },
  fungal: {
    id: 'fungal',
    name: 'Fungal',
    tagline: 'Glowing mushroom forests the size of skyscrapers.',
    description: 'Spore-filled air and colossal bioluminescent fungi. Weird, wonderful and alive.',
    hasOcean: true,
    oceanCoverage: 0.3,
    oceanColor: 0x3a5f8a,
    atmosphere: { color: 0xff9ae0, density: 1.2, breathable: false },
    temperature: 20,
    gravity: [0.8, 1.0],
    cloudCover: 0.4,
    biomes: { low: [Biome.Fungal, Biome.Swamp], mid: [Biome.Fungal, Biome.Meadow], high: [Biome.Rock, Biome.Fungal], peak: Biome.Rock, polar: Biome.Tundra, shore: Biome.Swamp, seabed: Biome.Ocean },
    features: { [Feature.AlienFlora]: 0.3, [Feature.Flowers]: 0.06, [Feature.Rocks]: 0.04, [Feature.Ruins]: 0.006 },
    palette: { land: 0x7a4f8a, lowland: 0x9a5fa0, highland: 0x5a4a6a, shore: 0xc9a9d0, snow: 0xf0e0f6, rock: 0x4a3a52 },
    defaultStyle: 'organic',
    needsOxygen: true,
    hazards: ['sporestorm', 'plague', 'kaiju', 'meteor'],
    resources: ['biotech', 'spores'],
    ringChance: 0.2,
    moons: [1, 3],
    frequency: [30, 42],
    ruggedness: 0.45,
  },
  tundra: {
    id: 'tundra',
    name: 'Tundra',
    tagline: 'Wind-swept steppes and boreal forests.',
    description: 'Cold plains, taiga and wide rivers. Hardy and resource-rich.',
    hasOcean: true,
    oceanCoverage: 0.4,
    oceanColor: 0x2a5f80,
    atmosphere: { color: 0x9fc4e6, density: 0.9, breathable: true },
    temperature: -8,
    gravity: [0.9, 1.1],
    cloudCover: 0.5,
    biomes: { low: [Biome.Tundra, Biome.Grass], mid: [Biome.Tundra, Biome.Forest], high: [Biome.Rock, Biome.Snow], peak: Biome.Snow, polar: Biome.Ice, shore: Biome.Beach, seabed: Biome.Ocean },
    features: { [Feature.Trees]: 0.25, [Feature.DenseTrees]: 0.08, [Feature.Rocks]: 0.06, [Feature.Ore]: 0.04, [Feature.IceDeposit]: 0.02 },
    palette: { land: 0x8a9a6a, lowland: 0x9aa878, highland: 0x7a7a6a, shore: 0xd8d0b0, snow: 0xf4f8ff, rock: 0x6a6a62 },
    defaultStyle: 'classic',
    needsOxygen: false,
    hazards: ['blizzard', 'wildfire', 'meteor', 'earthquake'],
    resources: ['timber', 'ore'],
    ringChance: 0.1,
    moons: [0, 2],
    frequency: [32, 42],
    ruggedness: 0.4,
  },
  machine: {
    id: 'machine',
    name: 'Machine World',
    tagline: 'An ancient ecumenopolis of metal plains.',
    description: 'The ruins of a planet-wide machine civilisation. Metal plates, data spires and forgotten power grids.',
    hasOcean: true,
    oceanCoverage: 0.2,
    oceanColor: 0x22e0ff,
    atmosphere: { color: 0x66ffee, density: 0.6, breathable: false },
    temperature: 5,
    gravity: [1.0, 1.5],
    cloudCover: 0.15,
    biomes: { low: [Biome.Metal], mid: [Biome.Metal, Biome.Rock], high: [Biome.Metal], peak: Biome.Metal, polar: Biome.Ice, shore: Biome.Metal, seabed: Biome.Metal },
    features: { [Feature.Ruins]: 0.06, [Feature.Ore]: 0.04, [Feature.GasVent]: 0.02 },
    palette: { land: 0x6a7480, lowland: 0x5a6470, highland: 0x8a94a0, shore: 0x4a5460, snow: 0xc0ccd8, rock: 0x3a4450 },
    defaultStyle: 'cyber',
    needsOxygen: true,
    hazards: ['nanites', 'solarflare', 'meteor', 'robot-uprising'],
    resources: ['data', 'alloys'],
    ringChance: 0.5,
    moons: [0, 2],
    frequency: [36, 48],
    ruggedness: 0.3,
  },
};

export const PLANET_TYPE_IDS = Object.keys(PLANET_TYPES) as PlanetTypeId[];
