import type { CorpusManifest } from './types';

/**
 * Continuity — spoiler-bounded story bible.
 * Odyssey demo at book 8. Places tab off. Hop = watermark.
 */
export const continuityManifest: CorpusManifest = {
  id: 'continuity',
  name: 'Continuity',
  tagline: 'Read up to your watermark. Nothing after it has a name yet.',
  identifier: 'id',
  linkGraph: 'crosslinks',
  hop: 'watermark',
  hopClock: { min: 1, max: 24, default: 8, unit: 'book' },
  hopCopy: {
    sealedTitle: 'This is after your watermark',
    sealedBody: '{title} continues after {unit} {clock}.',
    extraTitle: 'This is outside this bound',
    extraBody: '{title} is not on this side of the watermark.',
    unbornTitle: 'This has not happened yet',
    unbornBody: '{title} first appears after {unit} {clock}.',
    stay: 'Stay',
    openExtra: 'Open as Extra',
    stepPast: 'Step past and move watermark',
  },
  labels: {
    record: { singular: 'Passage', plural: 'Passages' },
    discover: 'Board',
    places: 'Atlas',
    saved: 'Canons',
    activity: 'Activity',
    search: 'Search',
    list: { singular: 'Canon', plural: 'Canons' },
    defaultList: 'Read later',
    quickFacts: 'At this watermark',
    searchPlaceholder: 'Search what you have already reached',
    placesSearchPlaceholder: 'Search places',
    discoverIntro: 'Board is what is safe at your watermark — no query needed. Sealed cards ask before they open. Unborn names stay hidden.',
    linkNoun: 'paths',
    talk: 'Notes',
    watchlist: 'Following',
    wordmark: 'Continuity',
  },
  features: {
    geo: false,
    media: false,
    languages: false,
    contribution: false,
    watchlist: false,
    talk: false,
    donate: false,
    packs: false,
    userPage: false,
    history: false,
    notifications: false,
    tone: false,
  },
  cardSources: [
    { id: 'featured', title: 'On deck', rail: 'today', enabledByDefault: true, requiresNetwork: false },
    { id: 'becauseYouRead', title: 'Because you just finished', rail: 'forYou', enabledByDefault: true, requiresNetwork: false },
    { id: 'onThisDay', title: 'Canon', rail: 'community', enabledByDefault: true, requiresNetwork: false },
    { id: 'random', title: 'Another passage', rail: 'forYou', enabledByDefault: false, requiresNetwork: false },
  ],
  languages: [{ code: 'en', name: 'English', nativeName: 'English' }],
  defaultLanguages: ['en'],
  auth: 'none',
  accountUnlocks: [],
  sensitiveCategories: [],
  violentCrimeCategories: [],
  defaultRegion: { latitude: 38.4, longitude: 20.7, latitudeDelta: 2.4, longitudeDelta: 2.4 },
  defaultRegionName: 'Ithaca',
  featuredDestinations: [],
  deepLink: { scheme: 'continuity', hosts: ['continuity.example'], recordPathPrefix: '/passage/' },
  legal: {
    license: 'Demo text for the Odyssey watermark. Not a published edition.',
    privacyUrl: 'https://continuity.example/privacy',
    termsUrl: 'https://continuity.example/terms',
  },
  accent: { light: '#8A5A2B', dark: '#E0B07A' },
};
